---
title: "PicoPure RNA Isolation Kit"
author: "Callum Malcolm"
date: "2023-06-13"
output:
  pdf_document: default
  html_document: default
---

*Note before starting:*  
  - Pre-heat block to 42C  
  - Pre-make DNAse treatment master mix (1.1n)  
  
|Component       |Volume|   MM volume  |
|:--------------|----|-----------------|
| DNAse I Stock | 5 $\mu$L |          |
| DNA Disgestion Buffer | 35 $\mu$L |          |  
  
  **Protocol** 
  
  1. Extract cells with 100 $\mu$L of Extraction Buffer (XB)  
    - Resuspend the cell pellet gently by pipetting  
    - DO NOT VORTEX  
  2. Incubate at 42C for 30min  
  3. Centrifuge sample at 3000xg for two minutes  
  4. Collect supernatant  
    - Can stop here and freeze RNA at 70C  
  5. Pre-condition the RNA Purification Column  
    - Add 250 $\mu$L Conditioning Buffer onto the purification column filter membrane  
    - Incubate RNA Purification Column with CB for 5min at RT  
    - Centrifuge purification column at 16000xg for 1 min  
  6. Pipette 100 $\mu$L of 70% Ethanol (EtOH) into cell extract    
    - Mix well by pipetting  
    - DO NOT VORTEX  
  7. Add cell extract to column  
  8. Centrifuge column for 2 minutes at 100 x g and then 16000 x g for 30s  
  9. Pipette 100 $\mu$L Wash Buffer 1 (W1) into the purification column and centrifuge for 1min at 8000 x g  
  10. Add 40 $\mu$L of DNAse treatment master mix to purification tube
  - Add directly onto membrane  
  11. Incubate at RT for 15 min  
  12. Pipette 40 $\mu$L Wash Buffer 1 (W1) onto purification column membrane and centrifuge at 8000 x g for 15 seconds  
  13. Pipette 100 $\mu$L Wash Buffer 1 (W2) into purification column membrane and centriguge for one minute at 8000 x g  
  14. Pipette 100 $\mu$L Wash Buffer 1 (W2) into purification column membrane and centriguge for two minutes at 16000 x g  
    - Check if any wash buffer remains in column and centrifuge again at 16000 x g for one minute to clear all the liquid  
  15. Transfer purification column to new 0.5mL tube   
    - Insert purification column/0.5mL assembly into 1.5mL tube for centrifugation   
  16. Pipette EB directly onto membrane of the purification column   
    - Gently touch tip to surface of membrane to ensure maximum absorption of EB into membrane   
    - Use 11 $\mu$L to 30 $\mu$L EB   
  17. Incubate purification column for one minute at room temperature  
  18. Centrifuge column for one minute at 1000 x g to distribute EB in column  
  19. Centrifuge column for one minute at 16000 x g to elute RNA  
    - Start RT immediately or store at -80C until use
  
  